### ISSUE TITLE
Can't get Flash or HHD

### ISSUE THREAD

**Issue by abbaty48** [node-usb/node-usb-example-electron#2]
everything seems to works fine, but i can't get my connected usb flash drive or any harddisk drive. it an only see my wired mouse.
am using 
Node.js 16.17.1, 
Chromium 108.0.5359.179, 
Electron 22.0.3,
Windows11

please any help

**Comment by axelzuzek** [comment]
I only see my wired keyboard and the (usb-controlled) monitor, but no other devices. 
Windows 10
Electron to 23.1.3

**Comment by thegecko** [comment]
Drives and keyboards are all HID devices, I recommend looking at the [node-hid library](https://github.com/node-hid/node-hid) for accessing this sort of devices.

**Comment by abbaty48** [comment]
thank you, I'll try to check that.
